# GLM IBM 

We fit GLM vital rates and produce a dataset using the fitted IBM models.

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.linalg import eig
import statsmodels.api as sm
import statsmodels.formula.api as smf
from ipm_utils import (
    survival_kernel_glm, 
    fecundity_kernel_glm, 
    mk_K, 
    sigmoid, 
    growth_fn_glm, 
    flowering_fn_glm, 
    survival_fn_glm, 
    seed_fn_glm, 
    new_recruits_fn_glm
    )

In [2]:
glm_df = pd.read_csv('baseline_ibm_data_1000.csv')

In [3]:
glm_df.head()

          z  Repr  Seeds  Surv        z1  age  alive  yr
0  0.510920     0    NaN   1.0  1.446648    0   True  45
1  1.770340     0    NaN   1.0  1.622350    3   True  62
2  0.587524     0    NaN   1.0  2.585566    0   True  76
3 -0.109235     0    NaN   0.0       NaN    0  False  75
4  0.120598     0    NaN   0.0       NaN    0  False  88

In [4]:
glm_df.describe()

,z,Repr,Seeds,Surv,z1,age,yr
count,1000.000000,1000.000000,30.000000,970.000000,418.000000,1000.000000,1000.000000
mean,0.482066,0.030000,2335.233333,0.430928,1.457030,0.747000,72.836000
std,1.070879,0.170673,2073.777541,0.495462,0.819888,1.273032,17.037705
min,-2.838371,0.000000,274.000000,0.000000,-0.570366,0.000000,1.000000
25%,-0.279494,0.000000,970.250000,0.000000,0.852123,0.000000,65.000000
50%,0.406070,0.000000,1778.000000,0.000000,1.453693,0.000000,79.000000
75%,1.243246,0.000000,2827.250000,1.000000,2.032793,1.000000,86.000000
max,3.695600,1.000000,9178.000000,1.000000,3.700061,7.000000,90.000000

In [5]:
#Growth
growth_data = glm_df.dropna(subset = ["z1"]).copy()
growth_model = smf.ols(formula="z1 ~ z", data=growth_data).fit()
growth_intercept = growth_model.params["Intercept"]
growth_slope = growth_model.params["z"]
growth_sd = np.sqrt(growth_model.scale)

print(growth_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     z1   R-squared:                       0.374
Model:                            OLS   Adj. R-squared:                  0.373
Method:                 Least Squares   F-statistic:                     248.7
Date:                Sat, 25 Jul 2026   Prob (F-statistic):           2.94e-44
Time:                        18:01:09   Log-Likelihood:                -411.66
No. Observations:                 418   AIC:                             827.3
Df Residuals:                     416   BIC:                             835.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9964      0.043     23.092      0.000       0.912       1.081
z              0.5591      0.035     15.770      0.000       0.489       0.629
==============================================================================
Omnibus:                        1.515   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.469   Jarque-Bera (JB):                1.593
Skew:                           0.115   Prob(JB):                        0.451
Kurtosis:                       2.803   Cond. No.                         2.34
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [6]:
#Flowering
flowering_model = smf.glm(formula="Repr ~ z", data=glm_df, family=sm.families.Binomial()).fit()
flowering_intercept = flowering_model.params["Intercept"]
flowering_slope = flowering_model.params["z"]
print(flowering_model.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                   Repr   No. Observations:                 1000
Model:                            GLM   Df Residuals:                      998
Model Family:                Binomial   Df Model:                            1
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -29.114
Date:                Sat, 25 Jul 2026   Deviance:                       58.229
Time:                        18:01:09   Pearson chi2:                     92.0
No. Iterations:                    11   Pseudo R-squ. (CS):             0.1904
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -17.7034      3.054     -5.797      0.000     -23.689     -11.718
z              6.6183      1.183      5.593      0.000       4.299       8.938
==============================================================================

In [7]:
# Survival
# Keep only non-flowering plants
survival_data = glm_df[glm_df["Repr"] == 0].copy()
survival_model = smf.glm(formula="Surv ~ z", data=survival_data, family=sm.families.Binomial()).fit()
survival_intercept = survival_model.params["Intercept"]
survival_slope = survival_model.params["z"]

print(survival_model.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                   Surv   No. Observations:                  970
Model:                            GLM   Df Residuals:                      968
Model Family:                Binomial   Df Model:                            1
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -594.45
Date:                Sat, 25 Jul 2026   Deviance:                       1188.9
Time:                        18:01:10   Pearson chi2:                     959.
No. Iterations:                     4   Pseudo R-squ. (CS):             0.1319
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.6578      0.079     -8.280      0.000      -0.814      -0.502
z              0.8356      0.078     10.753      0.000       0.683       0.988
==============================================================================

In [8]:
#Seeding
# Keep only flowering plants
seed_data = glm_df[glm_df["Repr"] == 1].copy()
seed_model = smf.glm(
    formula="Seeds ~ z",
    data=seed_data,
    family=sm.families.Poisson()
).fit()
seed_intercept = seed_model.params["Intercept"]
seed_slope = seed_model.params["z"]

print(seed_model.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  Seeds   No. Observations:                   30
Model:                            GLM   Df Residuals:                       28
Model Family:                 Poisson   Df Model:                            1
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -150.67
Date:                Sat, 25 Jul 2026   Deviance:                       23.263
Time:                        18:01:10   Pearson chi2:                     23.1
No. Iterations:                     5   Pseudo R-squ. (CS):              1.000
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.0037      0.035     28.526      0.000       0.935       1.073
z              2.1986      0.011    201.827      0.000       2.177       2.220
==============================================================================

In [9]:
#New Recruits
recruit_data = glm_df[glm_df["age"] == 0].copy()

recruit_mean = recruit_data["z"].mean()
recruit_sd = recruit_data["z"].std()
p_r_est = ((glm_df["age"] == 0).sum() / np.nansum(glm_df["Seeds"]))

print(recruit_mean)
print(recruit_sd)
print(p_r_est)

-0.08122094407670358
0.7558511996617439
0.008878484662489116

In [10]:
m_par_est = {
    "surv.int": survival_intercept,
    "surv.z": survival_slope,

    "flow.int": flowering_intercept,
    "flow.z": flowering_slope,

    "grow.int": growth_intercept,
    "grow.z": growth_slope,
    "grow.sd": growth_sd,

    "rcsz.int": recruit_mean,
    "rcsz.sd": recruit_sd,

    "seed.int": seed_intercept,
    "seed.z": seed_slope,

    "p.r": p_r_est
}

In [22]:
# NOTE: Increase initial population size from 250 to 500 to prevent extinction 
# from demographic stochasticity
n_years = 6
init_pop_size = 250 
rng = np.random.default_rng(10)

plant_sizes = rng.normal(
    loc = m_par_est['rcsz.int'],
    scale = m_par_est['rcsz.sd'],
    size = init_pop_size
 )

plant_ages = np.zeros(init_pop_size, dtype = int)
mean_age_history = [plant_ages.mean()]
simulation_records = []
recruits_per_year = []
year = 1
while (year != n_years) and (len(plant_sizes) < 5000):
    current_population_size = len(plant_sizes)
    print(f"Year {year}:Current Population Size = {current_population_size}")

    #Flowering
    flowered = rng.binomial(n = 1, p = flowering_fn_glm(plant_sizes, m_par_est))

    #Seeding
    number_flowering = flowered.sum()
    seed_counts = np.full(shape = len(plant_sizes), fill_value = np.nan)
    seed_counts[flowered == 1] = rng.poisson(lam = seed_fn_glm(plant_sizes[flowered == 1],m_par_est))
    total_seeds = np.nansum(seed_counts)

    #New Recruits Establishment
    if number_flowering == 0:
        number_recruits = 0
    else:
        # Each seed has some probability of becoming a new recruit
        number_recruits = rng.binomial(n = int(total_seeds), p = m_par_est["p.r"])
    recruits_per_year.append(number_recruits)

    #New Recruits Sizes
    recruit_sizes = rng.normal(loc = m_par_est["rcsz.int"], scale = m_par_est["rcsz.sd"], size = number_recruits)

    #Survival
    survived = np.full(shape = len(plant_sizes), fill_value = np.nan)

    non_flowering = (flowered == 0) #Flowering is fatal for monocarps
    survival_probabilities = survival_fn_glm(plant_sizes[non_flowering], m_par_est)

    survived[non_flowering] = rng.binomial(n = 1, p = survival_probabilities)


    #Growth for survivors and non-reproducers
    still_alive = ((flowered == 0) & (survived ==1))
    expected_next_size = (m_par_est["grow.int"] + m_par_est["grow.z"] * plant_sizes[still_alive])
    grown_sizes = rng.normal(loc = expected_next_size, scale = m_par_est["grow.sd"])

    next_year_size = np.full(len(plant_sizes), np.nan)
    next_year_size[still_alive] = grown_sizes

    for i in range(len(plant_sizes)):
        simulation_records.append({
            "z": plant_sizes[i],
            "Repr": flowered[i],
            "Seeds": seed_counts[i],
            "Surv": survived[i],
            "z1": next_year_size[i],
            "age": plant_ages[i],
            "alive": still_alive[i],
            "yr": year
        })

    plant_sizes = np.concatenate([recruit_sizes, grown_sizes])
    plant_ages = np.concatenate([np.zeros(number_recruits, dtype=int),plant_ages[still_alive] + 1])
    year += 1

sim_data = pd.DataFrame(simulation_records)

Year 1:Current Population Size = 250
Year 2:Current Population Size = 80
Year 3:Current Population Size = 67
Year 4:Current Population Size = 39
Year 5:Current Population Size = 124

In [23]:
sim_data.head()

          z  Repr  Seeds  Surv  z1  age  alive  yr
0 -0.915181     0    NaN   0.0 NaN    0  False   1
1 -0.629232     0    NaN   0.0 NaN    0  False   1
2 -0.672149     0    NaN   0.0 NaN    0  False   1
3  0.120573     0    NaN   0.0 NaN    0  False   1
4 -0.269111     0    NaN   0.0 NaN    0  False   1

In [26]:
sim_data.describe()

,z,Repr,Seeds,Surv,z1,age,yr
count,560.000000,560.000000,16.000000,544.000000,212.000000,560.000000,560.000000
mean,0.274511,0.028571,1658.000000,0.389706,1.337016,0.519643,2.476786
std,1.064106,0.166748,1812.467636,0.488132,0.828193,0.941760,1.617048
min,-2.299141,0.000000,158.000000,0.000000,-0.938620,0.000000,1.000000
25%,-0.484583,0.000000,842.250000,0.000000,0.776419,0.000000,1.000000
50%,0.141106,0.000000,1039.000000,0.000000,1.389974,0.000000,2.000000
75%,1.038216,0.000000,1512.000000,1.000000,1.894787,1.000000,4.000000
max,3.520590,1.000000,6257.000000,1.000000,3.520590,4.000000,5.000000

In [25]:
vr_func_est = {
    'repr': flowering_fn_glm, 
    'surv': survival_fn_glm,
    'seed': seed_fn_glm,
    'grow': growth_fn_glm,
    'new_recruits_fn': new_recruits_fn_glm
    }

In [15]:
n_big_matrix = 250

L = -2.7
U = 4

IPM_true = mk_K(
    n_mesh_points=n_big_matrix,
    m_par=m_par_est,
    lower_size= L,
    upper_size= U,
    vital_rate_functions= vr_func_est
)

In [16]:
eigenvalues_true, eigenvectors_true = np.linalg.eig(IPM_true["K"])
idx = np.argmax(eigenvalues_true.real)
lambda_true = eigenvalues_true[idx].real
eigenvector_true = eigenvectors_true[:, idx].real

print(lambda_true)
print(eigenvector_true.shape)

1.0976859008592306
(250,)

In [28]:
sim_data.to_csv('glm_ibm_dataset.csv', index=False)